# Generated by Django 4.2.7 on 2024-03-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('title', models.CharField(max_length=90)),
                ('core_line', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(to='client.tag')),
            ],
        ),
    ]
