# Generated by Django 4.2.7 on 2024-03-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_service_description_industries_casestudies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='industries',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
