# Generated by Django 4.2.7 on 2024-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_casestudies_name_alter_casestudies_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industries',
            name='square_image',
            field=models.ImageField(default=None, upload_to='services/'),
            preserve_default=False,
        ),
    ]
