# Generated by Django 4.2.7 on 2024-03-27 05:45

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_industries_square_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('slug', models.SlugField(max_length=90)),
                ('short_detail', models.CharField(max_length=200)),
                ('details', froala_editor.fields.FroalaField()),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='client_job_name_c6b586_idx')],
            },
        ),
        migrations.CreateModel(
            name='Applied_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('number', models.CharField(max_length=20)),
                ('email', models.CharField(db_index=True, max_length=90)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.job')),
            ],
        ),
    ]
