# Generated by Django 4.2.7 on 2024-03-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(to='client.tag'),
        ),
    ]
