# Generated by Django 4.2.7 on 2024-03-27 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Location', max_length=200),
        ),
    ]
